name:                chip8

dependencies:
- base >= 4.7 && < 5
- hspec
- bytestring
- array
- vty
- stm

ghc-options: [ -Wall , -Wcompat , -Widentities , -Wincomplete-record-updates , -Wincomplete-uni-patterns  , -Wmissing-home-modules , -Wpartial-fields , -Wredundant-constraints ]

library:
  source-dirs: src

executables:
  chip8-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options: [-threaded , -rtsopts , -with-rtsopts=-N ] 
    dependencies:
    - chip8

tests:
  chip8-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options: [-threaded , -rtsopts , -with-rtsopts=-N ] 
    dependencies:
    - chip8
